### ISSUE TITLE
Auto generate enums for encoder scripts

### ISSUE THREAD

**Issue by flobernd** [zyantific/zydis-db#8]
The encoder scripts currently contain duplicates of e.g. the `ZydisMnemonic` or `ZydisRegister` enum. As an improvement we should auto-generate them from the `C` code in the future.

**Comment by mappzor** [comment]
I have an idea to do this using 2 pure-python packages:

- [pcpp](https://github.com/ned14/pcpp) - C99 preprocessor
- [pycparser](https://github.com/eliben/pycparser) - C parser

This solution seems promising. I like customization options offered by pcpp because we might need them to get around compiler-specific stuff inside zycore.

**Comment by mappzor** [comment]
I played with those packages and made a small proof of concept. It works very well 😀 `ZYDIS_ATTRIB_*` is the worst because:

- it's defined with preprocessor defines instead of enum type - this requires some introspection into final internal state of the preprocessor but luckily all information is available in a fairly convenient fashion
- it's defined using expressions (bitshifts) rather than constants - requires some evaluation after parsing but `eval` can help here

By the way this whole issue is more about crash tool inside main Zydis repo. Code in this repo relies on `ZydisRegister` and it's because of `instruction-order-test`. The best solution here will be to get rid of that part. It's legacy and its C counterpart isn't even public.
